USE eldermoodai;

-- User Table
CREATE TABLE IF NOT EXISTS `user` (
    `id` BIGINT AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(50) NOT NULL UNIQUE,
    `phone` VARCHAR(20) UNIQUE,
    `email` VARCHAR(100) UNIQUE,
    `password_hash` VARCHAR(255) NOT NULL,
    `role` VARCHAR(20) NOT NULL COMMENT 'GUARDIAN, CAREGIVER, ADMIN',
    `status` VARCHAR(20) NOT NULL COMMENT 'ACTIVE, INACTIVE, PENDING_APPROVAL',
    `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    CONSTRAINT `chk_user_role` CHECK (`role` IN ('GUARDIAN', 'CAREGIVER', 'ADMIN')),
    CONSTRAINT `chk_user_status` CHECK (`status` IN ('ACTIVE', 'INACTIVE', 'PENDING_APPROVAL')),
    CONSTRAINT `chk_user_contact` CHECK (`phone` IS NOT NULL OR `email` IS NOT NULL)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户表';
